### ISSUE TITLE
Item IDs switching?

### ISSUE THREAD

**Issue by cj89898** [KaiKikuchi/BetterChunkLoader#15]
Sometimes when my server restarts, the chunks in which the BCLs are PLACED in (not loading) have switched item IDs. For example 64k ME drives turned into Heavy Duty Leggings. I put this into the Project Ozone 2 pack and it seems to be happening frequently.

**Comment by KaiKikuchi** [comment]
BetterChunkLoader uses the Forge API. That means that even if it was caused by a chunk loader, it's not BCL related. Any chunk loader that use Forge API would cause the issue. 
This is the first time I hear about this. Honestly I think it's not related to BCL.
I have no clue what's causing that, probably some bad mod doing some weird thing with block IDs.

BCL is being run on several different modpacks and it hasn't caused any issue. I would check your mods, plugins and/or server configuration.

**Comment by evernife** [comment]
Same occurred to me.

I started using the always online chunk loader for the last days and is seems to happens, mainly with tinkers items...

Can you set a configurable delay time for chunks to load?

**Comment by KaiKikuchi** [comment]
I hope you understand this is not related to BCL.

> Can you set a configurable delay time for chunks to load?

If you want to suggest a new feature, please make a new issue.
