### ISSUE TITLE
Run a scheduled task to make sure that the Chunk Loaders are there

### ISSUE THREAD

**Issue by Eufranio** [KaiKikuchi/BetterChunkLoader#18]
This, basically. Players can break chunk loaders with things that doesn't fire a BlockBreakEvent (like Annihillation Planes), and BCL will never know that the chunk loader was destroyed. My suggestion is to run a scheduled task like each 5 or 10 minutes, looping all chunk loader coords, to make sure that there really is a block, and the block is a chunk loader. If the block is empty, or with another block, the BCL would remove the chunk loading from the place.

**Comment by KaiKikuchi** [comment]
I don't want to affect servers performances. Chunk loaders are already checked on server load... and everyone restart their servers at least once a day. If the block is not a valid chunk loader the block won't load. Also this check is done on player login for online-only chunk loaders. Anyway I don't think players will be happy to replace their chunk loaders every time the server restarts. I think they'll avoid to use this trick because it doesn't give any real benefit. By default, chunk loaders are made with iron and diamond blocks, they're not expensive.

**Comment by Eufranio** [comment]
If the chunk loader blocks are expensive (my server), they would use it anyway, as I discovered right now (a lot of player didn't have real chunk loader blocks). I don't know how it checks, because after some tests, I discovered that the chunk will still being loaded even if the block isn't there (after server restarts). 

You don't need to replace all chunk loader, only check if there is a valid chunk loader block in the coords of the chunk loaders. If there is no valid blocks in the space, the chunk loader simply get purged.

**Comment by KaiKikuchi** [comment]
> I discovered that the chunk will still being loaded even if the block isn't there (after server restarts).

You have to document this very well, because from my tests the block check works just fine. Also looking at the code, it does a [block check](https://github.com/KaiKikuchi/BetterChunkLoader/blob/master/src/main/java/net/kaikk/mc/bcl/CChunkLoader.java#L104) on server start when [loading always-on chunk loaders](https://github.com/KaiKikuchi/BetterChunkLoader/blob/master/src/main/java/net/kaikk/mc/bcl/BetterChunkLoader.java#L78), and a block check when [the player joins the server](https://github.com/KaiKikuchi/BetterChunkLoader/blob/master/src/main/java/net/kaikk/mc/bcl/EventListener.java#L129) (for online-only chunk loaders).

**Comment by KaiKikuchi** [comment]
Also, the "/bcl purge" command does a block check too, and removes the chunk loader completely if the block doesn't exist. You can use a command scheduler plugin to run the command every 5-10 minutes.

**Comment by Eufranio** [comment]
Yep, the plugin is working perfectly, it was my fault, sorry!
